### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 2007,
  "mileage": 60000,
  "lng": 0,
  "lat": 0,
  "price": 45000
}
